### ISSUE TITLE
cannot import anotator

### ISSUE THREAD

**Issue by msalimbe1** [IBM/whcs-python-sdk#5]
I'm just trying to follow the documentation: https://cloud.ibm.com/apidocs/wh-acd?code=python#introduction

1 step: Install package 
`pip install --upgrade "watson-developer-cloud>=1.4.0"`

2 step: import
`from ibm_watson import AnnotatorForClinicalData`

But the import fails:

```bash
>>> from ibm_watson import AnnotatorForClinicalData
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'AnnotatorForClinicalData' from 'ibm_watson' (/usr/local/lib/python3.7/site-packages/ibm_watson/__init__.py)
```

I got ibm_watson installed

```bash
/Users/matisalimba/dev/functions 🌀 pip show ibm_watson
Name: ibm-watson
Version: 4.3.0
Summary: Client library to use the IBM Watson Services
Home-page: https://github.com/watson-developer-cloud/python-sdk
Author: IBM Watson
Author-email: watdevex@us.ibm.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: ibm-cloud-sdk-core, requests, python-dateutil, websocket-client
Required-by: 
```

Also watson-developer-cloud (as advised `pip install --upgrade "watson-developer-cloud>=1.4.0"`

```bash
/Users/matisalimba/dev/functions 🌀 pip show watson-developer-cloud
Name: watson-developer-cloud
Version: 2.10.1
Summary: Client library to use the IBM Watson Services
Home-page: https://github.com/watson-developer-cloud/python-sdk
Author: Jeffrey Stylos
Author-email: jsstylos@us.ibm.com
License: Apache 2.0
Location: /usr/local/lib/python3.7/site-packages
Requires: python-dateutil, websocket-client, requests
Required-by: 
```

**Comment by srcarrier** [comment]
Thank you for reporting this @msalimbe1 
You caught us in the midst of externalizing this SDK and our documentation hasn't quite caught up yet.
We'll get the documentation up-to-speed here in short order. Apologies for that.

In the meantime ...

**To install:**
$ pip install ibm-whcs-sdk=0.0.10

**Some sample code:**

```
import ibm_whcs_sdk.annotator_for_clinical_data as acd

service = acd.AnnotatorForClinicalDataV1(iam_apikey = "{YOUR_API_KEY}", url = "https://us-east.wh-acd.cloud.ibm.com/wh-acd/api")

resp = service.analyze_with_flow("wh_acd.ibm_clinical_insights_v1.0_standard_flow", "Patient has lung cancer, but did not smoke. She may consider chemotherapy as part of a treatment plan.")
```

Let us know if you have any further questions or experience any further issues.
I'll add another comment once the doc has been updated.

Thank you

**Comment by msalimbe1** [comment]
Thank you @srcarrier . Dan contacted me and helped me get going (similar to your feedback). I'm all set. I know this is an ongoing development and docs will be updated. Thank you for your help!

**Comment by srcarrier** [comment]
**Documentation has been updated:**
https://cloud.ibm.com/apidocs/wh-acd?code=python#introduction
